### ISSUE TITLE
Dissolution Chamber doesn't yield essentia from Cobblestone

### ISSUE THREAD

**Issue by TerrariaSackboy** [CumulusMC/Art-of-Alchemy#16]
Art of Alchemy version 1.0.0-rc3 on Minecraft 1.16.3

# Issue

Using the normal dissolution chamber, cobblestone never yields essentia. This does work in the dissolution chamber+, however.

# Layman's Diagnosis

Cobblestone does actually yield materia from the Calcinator, so I've done some amateur sleuthing and come to a conclusion.

[BlockEntityDissolver](https://github.com/CumulusMC/Art-of-Alchemy/blob/1.16/src/main/java/io/github/synthrose/artofalchemy/blockentity/BlockEntityDissolver.java) does not use the stochasticRound function. [BlockEntityCalcinator](https://github.com/CumulusMC/Art-of-Alchemy/blob/1.16/src/main/java/io/github/synthrose/artofalchemy/blockentity/BlockEntityCalcinator.java), on the other hand, does. Cobblestone with a normal dissolution chamber has a `factor` of 0.5, so I think it just adds 0 to the EssentiaStack every time.

**Comment by Sturmlilie** [comment]
Yeah, I've noticed that in general, the stochastic weights in the recipes are being ignored. Will have to investigate whether this is intentional or not.

**Comment by Sturmlilie** [comment]
Fixed on `1.16-next`; I'll wait a while longer on LibGui to merge my PRs, then push out an rc4.
