### ISSUE TITLE
Essentia conduits are missing Cs Source

### ISSUE THREAD

**Issue by KevinUwO** [CumulusMC/Art-of-Alchemy#18]
When i put them down they don't have textures.

**Comment by Sturmlilie** [comment]
Please make sure you're not using either Sodium or Optifabric as those lack support for the fabric rendering API and are thus unsupported.

**Comment by KevinUwO** [comment]
I am using Fabric.

**Comment by Sturmlilie** [comment]
Please provide me a list of all mods you're using and Minecraft version.
