### ISSUE TITLE
Missing textures on the essentia pipes on the 1.16.4 and 1.16.5 versions

### ISSUE THREAD

**Issue by Llightfoot135** [CumulusMC/Art-of-Alchemy#28]
![2021-07-15_04 16 44](https://user-images.githubusercontent.com/6856090/125779493-c0fcab1c-6765-4d29-8440-dd9cb6fb3d49.png)

I have done no modifications of these files myself, the textures for the essentia pipes just stopped working, even between versions, though i most often use the 1.16.4 version.

**Comment by Llightfoot135** [comment]
I believe it is some conflict with the Sodium add on, as it does change some rendering in the game.

**Comment by Vaerian** [comment]
Yeah unfortunately Sodium is not compatible with the fabric rendering api. I believe that they're working on it though. You'll find it bricks nearly any mod that tries to do custom rendering.

**Comment by Sturmlilie** [comment]
@Llightfoot135  You may want to give [Indium](https://github.com/comp500/Indium) a try, which claims to enable FRAPI support under Sodium (which AoA uses to render pipes).
