### ISSUE TITLE
Essentia Conduit lost texture

### ISSUE THREAD

**Issue by DCthePagan** [CumulusMC/Art-of-Alchemy#48]
I added the Art of Alchemy Memorium mod to a modpack(Medieval Minecraft) I'm using for a self-hosted server, got to using essentia conduits, and they only show the pink and black no-texture block. Since I had trouble with some other issues anyways I replaced the .jar from the memorium mod to the Art of Alchemy Continued mod. However, there was no change in the texture.

**Comment by DCthePagan** [comment]
Upon closer inspection into the resolved issues, I realize this is an already known issue. However, though I'm not sure it makes much of a difference, I'm in 1.17 and still having this issue, additionally, the modpack I'm using combines Iris and Sodium into one .jar file, and I don't know how to completely remove them either to resolve this issue.

**Comment by KyGost** [comment]
> I replaced the .jar from the memorium mod to the Art of Alchemy Continued mod.

What do you mean by this?
Continued and Memoriam are isolated branches of the same original mod.
They are not to be used together.
